version: '2'

services:
  couchbase:
    image: couchbase:enterprise-6.0.3
    volumes:
      - "./couchbase:/opt/couchbase/var"
    ports:
      - "8091:8091"
  web-api:
    build:
      context: web-api
      dockerfile: Dockerfile
    container_name: "web-api-core"
    ports: 
      - "5000:80"
    environment:
      Couchbase__Servers__0: http://couchbase:8091/
    depends_on:
      - couchbase
    command: ["./wait-for-it.sh", "http://couchbase:8091"]
  
